import { GAMES } from './gamesInfo.js';

export const gamesParsing = {
  'кол': GAMES.COLONIZERS,
  'кал': GAMES.COLONIZERS,
  'коло': GAMES.COLONIZERS,
  'колония': GAMES.COLONIZERS,
  'колонист': GAMES.COLONIZERS,
  'колонисты': GAMES.COLONIZERS,
  'колонизаторы': GAMES.COLONIZERS,
  'код': GAMES.CODENAMES,
  'коды': GAMES.CODENAMES,
  'коднэмс': GAMES.CODENAMES,
  'коднэймс': GAMES.CODENAMES,
  'коднеймс': GAMES.CODENAMES,
  'ц': GAMES.CITADELS,
  'цит': GAMES.CITADELS,
  'циты': GAMES.CITADELS,
  'цыты': GAMES.CITADELS,
  'цитадель': GAMES.CITADELS,
  'цитадели': GAMES.CITADELS,
  'р': GAMES.PAINTING,
  'рис': GAMES.PAINTING,
  'рисовач': GAMES.PAINTING,
  'рисовать': GAMES.PAINTING,
  'рисовалка': GAMES.PAINTING,
  'х': GAMES.HANABI,
  'хнб': GAMES.HANABI,
  'ханаби': GAMES.HANABI,
  'ханабич': GAMES.HANABI,
  'г': GAMES.GNOMES,
  'в': GAMES.GNOMES,
  'гв': GAMES.GNOMES,
  'г-в': GAMES.GNOMES,
  'гном': GAMES.GNOMES,
  'гномы': GAMES.GNOMES,
  'вредитель': GAMES.GNOMES,
  'вредители': GAMES.GNOMES,
  'гномы вредители': GAMES.GNOMES,
  'гномы-вредители': GAMES.GNOMES,
  'тикет': GAMES.TICKET,
  'тикит': GAMES.TICKET,
  'ticket': GAMES.TICKET,
  'ttr': GAMES.TICKET,
  't2r': GAMES.TICKET,
  'поезда': GAMES.TICKET,
  'паровозы': GAMES.TICKET,
  'вагоны': GAMES.TICKET,
  'эрудит': GAMES.ERUDIT,

  'тест': GAMES.TEST,
  'test': GAMES.TEST,
};
